name: MASPENK V27 Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK
        run: |
          sdkmanager "platforms;android-35" "build-tools;35.0.0"

      - name: Extract MASPENK project
        run: |
          rm -rf maspenk_build
          mkdir -p maspenk_build
          unzip -q maspenk-v28-native.zip -d maspenk_build
          DIR=$(find maspenk_build -name settings.gradle -type f -print -quit | xargs dirname)
          if [ -z "$DIR" ]; then
            echo "settings.gradle tidak ditemukan"
            exit 1
          fi
          echo "PROJECT_DIR=$DIR" >> "$GITHUB_ENV"
      - name: Enable AndroidX
        run: echo "android.useAndroidX=true" >> "$PROJECT_DIR/gradle.properties"
      - name: Build APK
        run: |
         cd "$PROJECT_DIR"
         gradle --no-daemon assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: maspenk-v27-apk
          path: |
            **/build/outputs/apk/debug/*.apk
